#!/usr/bin/env python3
import serial
import time
import numpy as np
import RPi.GPIO as GPIO
import asyncio

class irsensorReader:
	def __init__(self, exit_event, GPIO_SENSOR1):
		self.GPIO_SENSOR1 = GPIO_SENSOR1
		self.exit_event = exit_event
        
		#sensor1 = 14
		
		GPIO.setmode(GPIO.BCM)
		GPIO.setup(GPIO_SENSOR1,GPIO.IN, pull_up_down = GPIO.PUD_UP)

	def readSensor(self):
		async def IRcheck():
			await asyncio.sleep(1)
			irValue = GPIO.input(sensor)
			if irValue:
				print('NOT DETECTED')
				
			else:
				print('DETECTED')

		async def main():
			print('IR Sensor Ready')

			try:
				while True:
					await IRcheck()
			except KeyboardInterrupt:
				GPIO.cleanup()

		asyncio.run(main())






